INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'ГенДир');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'ИспДир');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'Кадров');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'Юридический');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'Финансовый');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(1,'БухУчета');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(2,'Клиент');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(2,'Архив 1','Чайковского');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(2,'Архив 2','Разъезжая');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(2,'Финотдел');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(2,'ЮрОтдел');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(2,'БухОтдел');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Цилюрик О','Цилюрик Ольга');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Максименко','Максименко Елена');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Мешкова В','Мешкова Варвара');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Пивнев','Пивнев Евгений');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Цилюрик С','Цилюрик Светлана');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Быхалова','Быхалова Татьяна');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Кузьмина','Кузьмина Елена');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Коряшкина','Коряшкина Екатерина');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Кулик','Кулик Ирина');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Улицкая','Улицкая Юлия');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Новикова','Новикова Галина');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Барышева','Барышева Ольга');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Царева','Царева Елена');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Акулич','Акулич Мария');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Кулаева','Кулаева Елена');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Мешкова Т','Мешкова Татьяна');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Рожкова','Рожкова Светлана');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Скворцова','Скворцова Юлия');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Григорьева','Григорьева Елена');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Березина','Березина Оксана');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Мешкова И','Мешкова Ирина');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(3,'Синькова','Синькова Александра');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Первичка клиент');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Первичка Кадар');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Первичка ВФ');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(4,'Учредиловка','учредительные / рег. документы');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Образец');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(4,'Отчет','Отчет нерегламентированный');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Отчетность');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(4,'Инструкция');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Договор');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Счет');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'СФ','Счет-фактура');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Акт');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Накладная');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'ТТН','трансп.накл');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Письмо');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Доверенность');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'ПП','пл.поручение');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'РегФорма','регистрационная форма');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Устав');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Баланс');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'ОПУ','Отчет о приб. и убытках');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Декларация НДС');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Декларация прибыль');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'Декларация имущество','Декларация имущество и т.д.');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Приказ');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Протокол');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Решение');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(5,'Оборотка','оборотно-сальдовая ведомость');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Ведомость');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Табель');
INSERT INTO dasarchive_tagitem (group_id, name) VALUES(5,'Реестр');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Аврора-авто','ООО Аврора-авто');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Автотранс','ООО "Автотранс"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Академия','Академия Странствий БОО');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Алга Трэвел','ООО "Алга трэвел"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Аллан Берген','ООО "ТК Аллан БЕРГЕН"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Балт-Металл','ООО "Балт-Металл"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'БелОвощТорг','ООО БелОвощТорг');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Борисов, ИП','Борисов ИП');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Ведньер II','ООО Ведньер II');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Вигал','ООО Вигал М.Р.');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Вилинская, ИП','ИП Вилинская');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Восьмерка','ООО "ПЦ "Восьмерка"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ГорМедЦентр','ООО "ГорМедЦентр"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Гринхиллс','ООО "Гринхиллс Инвест"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ДЛХ-СПб','ООО "ДЛХ-Санкт-Петербург"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Ермилова, ИП','ИП Ермилова О.В.');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Зодиак','ООО "Зодиак"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Зычков, ИП','ИП Зычков');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Карамель','ООО Карамель');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'КриаСофт','ООО "КриаСофт"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Кушковский, ИП','ИП Кушковский');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Луч-100','ООО Луч-100');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Ляпкало, ИП','ИП Ляпкало Л.М.');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Металлодизайн','ООО "Металлодизайн"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Монитэкс','ООО МОНИТЭКС');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Назарова, ИП','ИП Назарова О.С.');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Нано-Глаз','ООО "Нано-Глаз"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Наутилус СПб','ООО "Наутилус СПб"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'НеваТест','ООО НеваТест');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Нефеш','ООО НЕФЕШ СПА');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Орион-Центр','ООО "Орион-Центр"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Павленко, ИП','ИП Павленко');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Панферов, ИП','ИП Панферов');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Петронефть','ЗАО ФПГ "Петронефть"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Поверенный','ООО "ЮК "Поверенный в дела"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Подъем','ООО "Подъем"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Подъем СК','ООО СК Подъем');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Прокуратор','ООО "НПО "Прокуратор"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ПСК С-З','ООО ПСК С-З');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ПЭС','ООО ПЭС');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'РосАудитСервис','ООО "РосАудитСервис"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Русь-Мастер','ООО "Русь-Мастер"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Свит-Груп','ООО СВИТ-Груп');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Соффид','ООО СОФФИД');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Спектр','ООО "Спектр"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Спецтехавтоматика','ООО "Спецтехавтоматика"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Степанцов, ИП','ИП Степанцов А.А.');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Сытник, ИП','ИП Сытник');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Татлин, ИП','ООО Татлин');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ТеатрТанго','ООО "ТеатрТанго"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Технологии будущего','ООО "Технологии будущего"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Топливо','ООО "Топливо и транспорт"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Фертман, ИП','ИП Фертман');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Фуд Форвард','ООО "Фуд Форвард"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Харламов, ИП','ИП Харламов');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Холидэй Люкс','ООО Холидэй Люкс');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Хорлунов, ИП','ИП Хорлунов');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Цезар-М','ООО Цезар-М');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'Эко-Техник','ООО "Эко-Техник"');
INSERT INTO dasarchive_tagitem (group_id, name, comment) VALUES(6,'ЭО ПТР','ООО "ЭО ПТР"');
